### ISSUE TITLE
Use image-difference over image-diff

### ISSUE THREAD

**Issue by oliviertassinari** [shcoder-ru/guit#2]
[image-diff](https://github.com/uber-archive/image-diff) is no longer maintained, I ended up rewriting it with the latest node standard.
[image-difference](https://github.com/argos-ci/image-difference) should run x4 faster based on [the benchmark](https://github.com/argos-ci/image-difference#benchmark).

**Comment by uxter** [comment]
Thank you for your offer! Soon I'll start the new major version 2 and I'll review your solution as a dependency. [guit](https://github.com/shcoder-ru/guit) is to be divided into some packages and one of them will likely use [image-difference](https://github.com/argos-ci/image-difference).

**Comment by oliviertassinari** [comment]
@shcoder-ru Let me know if you have any issue with that dependency, I can help.

**Comment by uxter** [comment]
I'll be sure to let you know, if there's a problem. Thanks a lot, @oliviertassinari.
